
version: '3.7'

services:

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.8
    container_name: elasticsearch
    environment:
      TZ: Europe/Amsterdam
      cluster.name: um-demo
      node.name: node-1
      cluster.initial_master_nodes: node-1
      bootstrap.memory_lock: true
      ES_JAVA_OPTS: -Xms512m -Xmx512m
    ulimits:
      memlock:
       soft: -1
       hard: -1
    volumes:
      - esdata1:/usr/share/elasticsearch/data
    ports:
      - "8084:9200"
    networks:
      - vng-net


  werkzoekende-bron:
    image: vngrci/werkzoekendenprofielen-bron:latest
    container_name: werkzoekende-bron
    environment:
      - "BRW_SERVER_PORT=8080"
      - "BRW_SERVER_ADDRESS=0.0.0.0"
      - "BRW_LOGGING_LEVEL_COMMON_REQUEST=DEBUG"
      - "BRW_LOGGING_LEVEL=INFO"
      - "BRW_LOGGING_FILE_PATH=."
      - "BRW_LOGGING_FILE_NAME=app.log"
      - "BRW_JWT_ISSUER_URI=https://um-demo.csp-nijmegen.nl/auth/realms/um-demo-realm"
      - "BRW_CONSOLE_ENABLED=true"
      - "BRW_DATASOURCE_URL=jdbc:h2:./werkzoekende-bemiddelaar;DB_CLOSE_ON_EXIT=FALSE;AUTO_RECONNECT=TRUE"
      - "BRW_DATASOURCE_DRIVER=org.h2.Driver"
      - "BRW_DATASOURCE_USERNAME=sa"
      - "BRW_DATASOURCE_PASSWORD="
      - "BRW_DATABASE_PLATFORM=org.hibernate.dialect.H2Dialect"
      - "BRW_HIBERNATE_DDL=update"
      - "BRW_ELASTICSEARCH_URL=elasticsearch:9200"
      - "BRW_MAX_AMOUNT_RESPONSE=100"
    networks:
      - vng-net
    depends_on:
      - elasticsearch
    ports:
      - 8080:8080
    restart: always


        


volumes:
  esdata1:
    driver: local

networks:
  vng-net:
    name: vng-net
    driver: bridge
