_format_version: "2.1"
_transform: true

services:

# Health check for AWS loadbalancer
  - name: health
    url: https://example.com
    routes:
      - name: check
        paths: 
          - /alive
        methods:
        - GET

# Camel adapter
  - name: camel-adapter
    url: http://camel-adapter.um-demo.local:8080
    routes:
      - name: adapter
        paths:
          - /gateway/camel
        strip_path: false 
        methods:
        - POST

# Van 'UM Werkzoekende-bemiddelaar' naar 'de centrale voorziening buiten UM'
  - name: vum-werkzoekende-vraag
    
    # De VUM centrale voorziening
    url: https://profiel-stub.testdorp.nl/api/v1
    # De Externe Profielen Stub
    # url: https://vum-cv.{host}.nl/api/v1
    
    tags:
      - VUM-BMW1
      - VUM-BMW2
    
    routes:
      - name: vum-werkzoekende-vraag
        paths:
          - /gateway/vumprofielvraag
        strip_path: true
        methods:
        - GET
        - POST

# Van 'UM Vacature-bemiddelaar' naar 'de centrale voorziening buiten UM'
  - name: vum-vacature-vraag
    
    #   De VUM centrale voorziening 
    url: https://vacature-stub.testdorp.nl/api/v1
    #   De Externe Vacature Stub
    #    url: https://vum-vac.{host}.nl/api/v1
    
    tags:
      - VUM-BMV1
      - VUM-BMV2
    
    routes:
      - name: vum-vacature-vraag
        paths:
          - /gateway/vumvacaturevraag
        strip_path: true

# Van 'VUM/STUB' naar 'UM Werkzoekende-bron'
  - name: vum-werkzoekende-bron
    url: http://werkzoekende-bron.um-demo.local:8080
        
    tags:
     - VUM-BRW1
     - VUM-BRW2
    
    routes:
      - name: vum-backend-werkzoekende-bron
        paths:
          - /gateway/v1/werkzoekendenProfielen/matches
        strip_path: true
        methods:
        - GET
        - POST

# Van 'VUM/STUB' naar 'UM Vacature-bron'
  - name: vum-vacature-bron
    url: http://vacatures-bron.um-demo.local:8080
    
    tags:
     - VUM-BRV1
     - VUM-BRV2
    
    routes:
      - name: vum-backend-vacature-bron
        paths:
          - /gateway/v1/vacatures/matches
        strip_path: true
        methods:
        - GET
        - POST

###################################
## Routes to internal containers ##
###################################

# Van 'UM GUI' en van 'VUM/STUB' callback naar 'UM Werkzoekende-bemiddelaar'
  - name: werkzoekende-bemiddelaar
    url: http://werkzoekende-bemiddelaar.um-demo.local:8080
    
    tags:
     - UM-BMW1
     - UM-BMW2
     - UM-BMW3
     - UM-BMW4
     - VUM-BMW3
    
    routes:
      - name: werkzoekende-bemiddelaar
        paths:
          - /gateway/aanvraagwerkzoekende
        strip_path: false
        methods:
        - GET
        - POST

# Van 'UM GUI' naar 'UM Werkzoekende-bron'
  - name: werkzoekende-bron
    url: http://werkzoekende-bron.um-demo.local:8080
    
    tags:
     - UM-BRW1
     - UM-BRW2
    
    routes:
      - name: backend-werkzoekende-bron
        paths:
          - /gateway/werkzoekende
        strip_path: false
        methods:
        - GET
        - POST

# Van 'UM GUI' en van 'VUM/STUB' callback naar 'UM Vacature-bemiddelaar'
  - name: vacature-bemiddelaar
    url: http://vacatures-bemiddelaar.um-demo.local:8080
    
    tags:
     - UM-BMV1
     - UM-BMV2
     - UM-BMV3
     - UM-BMV4
     - VUM-BMV3    
    
    routes:
      - name: vacature-bemiddelaar
        paths:
          - /gateway/aanvraagvacature
        strip_path: false

# Van 'UM GUI' naar 'UM Vacature-bron'
  - name: vacature-bron
    url: http://vacatures-bron.um-demo.local:8080
    
    tags:
     - UM-BRV1
     - UM-BRV2
    
    routes:
      - name: vacature-bron
        paths:
          - /gateway/vacature
        strip_path: false

plugins:
- name: cors
  config: 
    origins:
    - '*'
    headers:
    - Accept
    - Accept-Version
    - Content-Length
    - Content-MD5
    - Content-Type
    - Date
    - X-Auth-Token
    - Authorization
    methods:
    - GET
    - POST
    - PUT
    - DELETE
    - OPTIONS
    exposed_headers:
    - X-Auth-Token
    credentials: true
    max_age: 3600
    preflight_continue: true
- name: request-termination
  service: health
  enabled: true
  config: 
    status_code: 200
    message: Alive!